name: "Terraform Lint and Security Plan"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform_validation:
    name: "Lint, Validate & Plan"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Check Formatting
        run: terraform fmt -check -recursive

      - name: Initialize Workspace
        run: |
          cd terraform/environments/prod
          terraform init -backend=false

      - name: Validate Syntax
        run: |
          cd terraform/environments/prod
          terraform validate
